"use client";

import { useState } from "react";
import { CalendarCheck, Check, ChevronRight, Search, ShieldCheck } from "lucide-react";
import type { Lead } from "@/lib/types";

export function BookingVerification({ leads, notify, onUpdate }: { leads: Lead[]; notify: (message: string) => void; onUpdate: (lead: Lead) => void }) {
  const pending = leads.filter((lead) => lead.status === "Booking Recorded Pending Verification");
  const [selected, setSelected] = useState<Lead | null>(null);
  const [outcome, setOutcome] = useState("Booking found on practice calendar");
  function verify() {
    if (!selected) return;
    if (outcome === "Booking found on practice calendar") onUpdate({ ...selected, status: "Patient Booked and Verified", latestOutcome: "Booking verified by manager", nextAction: "Completed" });
    notify(`${selected.patient}: ${outcome}`); setSelected(null);
  }
  return <>
    <div className="page-head"><div><h1>Booking verification</h1><p>Compare recorded patient requests against the official practice calendar.</p></div><button className="btn btn-secondary" onClick={() => notify("Check the official practice calendar manually, then record whether the booking was found, changed, cancelled, or needs follow-up.")}><CalendarCheck size={14} />Calendar check guide</button></div>
    <div className="metric-grid" style={{gridTemplateColumns:"repeat(4,1fr)"}}>{[["Awaiting verification",String(pending.length),"Live pending bookings"],["Verified this month","0","No verified bookings yet"],["Not found","0","No calendar mismatches"],["Average verification time","—","Starts after first verification"]].map((row,i)=><div className={`metric-card ${["orange","teal","rose","blue"][i]}`} key={row[0]}><div className="metric-label">{row[0]}</div><div className="metric-value">{row[1]}</div><div className="metric-trend">{row[2]}</div></div>)}</div>
    <div className="toolbar"><div className="searchbar"><Search size={14}/><input placeholder="Search patient or account..." /></div><select className="select"><option>All employees</option></select><select className="select"><option>Oldest first</option><option>Newest first</option></select></div>
    <div className="card"><div className="card-head"><div><div className="card-title">Bookings awaiting a calendar check</div><div className="card-sub">Employee-recorded requests remain pending until a manager verifies them</div></div></div>{pending.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Patient</th><th>Recorded by</th><th>Preferred date</th><th>Preferred time</th><th>Confidence</th><th>Recorded</th><th></th></tr></thead><tbody>{pending.map((lead)=><tr key={lead.id}><td><strong>{lead.patient}</strong><br/><small>{lead.account}</small></td><td>{lead.assignedTo}</td><td><strong>Captured on lead</strong></td><td>Captured on lead</td><td><span className="badge standard">Pending verification</span></td><td>Live record</td><td><button className="btn btn-soft" onClick={()=>setSelected(lead)}>Verify <ChevronRight size={12}/></button></td></tr>)}</tbody></table></div> : <div className="empty-page" style={{ boxShadow: "none" }}><div className="empty-icon"><CalendarCheck size={25}/></div><h2>No bookings awaiting verification</h2><p>When employees record patient bookings, they will appear here for manager calendar checks.</p></div>}</div>
    {selected && <div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={event=>event.stopPropagation()}><div className="modal-head"><strong>Verify booking · {selected.patient}</strong><button className="icon-btn" onClick={()=>setSelected(null)}>×</button></div><div className="modal-body"><div className="callout"><ShieldCheck size={15}/><span>Check the official practice calendar before choosing an outcome. This creates a manager-signed audit record.</span></div><div className="form-field"><label>Verification outcome</label><select className="form-control" value={outcome} onChange={event=>setOutcome(event.target.value)}><option>Booking found on practice calendar</option><option>Booking not found</option><option>Booking date changed</option><option>Patient cancelled</option><option>Needs follow-up</option></select></div><div className="form-field" style={{marginTop:12}}><label>Manager verification notes</label><textarea className="form-control" placeholder="Calendar reference, changed date, or follow-up detail..." /></div></div><div className="modal-actions"><button className="btn btn-secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="btn btn-primary" onClick={verify}><Check size={14}/>Save verification</button></div></div></div>}
  </>;
}
