"use client";

import { ArrowDownToLine, Pencil, Plus, Search, Sparkles } from "lucide-react";
import { medicalAids } from "@/lib/mock-data";

export function MedicalAidView({ notify }: { notify:(message:string)=>void }) {
  return <><div className="page-head"><div><h1>Medical Aid Intelligence</h1><p>Configurable opportunity scoring—kept in your database, never buried in code.</p></div><div className="head-actions"><button className="btn btn-secondary" onClick={()=>notify("Scoring table exported")}><ArrowDownToLine size={14}/>Export</button><button className="btn btn-primary" onClick={()=>notify("New medical aid option ready to configure")}><Plus size={14}/>Add option</button></div></div>
  <div className="metric-grid" style={{gridTemplateColumns:"repeat(4,1fr)"}}>{[["Configured options","47","Across 12 schemes"],["Premium opportunities","398","34% of active leads"],["Unmatched options","23","Needs scoring review"],["Average quality score","76","+4 after latest review"]].map((row,i)=><div className={`metric-card ${["teal","orange","rose","violet"][i]}`} key={row[0]}><div className="metric-label">{row[0]}</div><div className="metric-value">{row[1]}</div><div className="metric-trend">{row[2]}</div></div>)}</div>
  <div className="toolbar"><div className="searchbar"><Search size={14}/><input placeholder="Search scheme or option…"/></div><select className="select"><option>All categories</option><option>Premium</option><option>High</option><option>Medium</option><option>Low</option><option>Unknown</option></select></div>
  <div className="card"><div className="card-head"><div><div className="card-title">Option scoring table</div><div className="card-sub">Scores influence prioritisation, but never close or delete a patient journey</div></div><Sparkles size={16} color="#c19038"/></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Scheme</th><th>Option</th><th>Quality score</th><th>Category</th><th>Active leads</th><th>Notes</th><th></th></tr></thead><tbody>{medicalAids.map(item=><tr key={item.scheme+item.option}><td><strong>{item.scheme}</strong></td><td>{item.option}</td><td><div className="score"><div className="score-bar"><i style={{width:`${item.score}%`}}/></div><strong>{item.score}</strong></div></td><td><span className={`badge ${item.category === "Premium" ? "premium" : item.category === "High" ? "high" : "standard"}`}>{item.category}</span></td><td>{item.leads}</td><td>{item.note}</td><td><button className="icon-btn" onClick={()=>notify(`${item.option} is ready to edit`)}><Pencil size={12}/></button></td></tr>)}</tbody></table></div></div></>;
}
