"use client";

import { ArrowDownToLine, Plus, Search, Sparkles } from "lucide-react";

export function MedicalAidView({ notify }: { notify:(message:string)=>void }) {
  return <><div className="page-head"><div><h1>Medical Aid Intelligence</h1><p>Configurable opportunity scoring — kept in your database, never buried in code.</p></div><div className="head-actions"><button className="btn btn-secondary" onClick={()=>notify("No scoring rows to export yet")}><ArrowDownToLine size={14}/>Export</button><button className="btn btn-primary" onClick={()=>notify("Medical aid scoring setup is ready for live configuration")}><Plus size={14}/>Add option</button></div></div>
  <div className="metric-grid" style={{gridTemplateColumns:"repeat(4,1fr)"}}>{[["Configured options","0","Add schemes and options"],["Premium opportunities","0","No leads generated yet"],["Unmatched options","0","Imports will populate review needs"],["Average quality score","—","No scoring data yet"]].map((row,i)=><div className={`metric-card ${["teal","orange","rose","violet"][i]}`} key={row[0]}><div className="metric-label">{row[0]}</div><div className="metric-value">{row[1]}</div><div className="metric-trend">{row[2]}</div></div>)}</div>
  <div className="toolbar"><div className="searchbar"><Search size={14}/><input placeholder="Search scheme or option..."/></div><select className="select"><option>All categories</option><option>Premium</option><option>High</option><option>Medium</option><option>Low</option><option>Unknown</option></select></div>
  <div className="card"><div className="card-head"><div><div className="card-title">Option scoring table</div><div className="card-sub">Scores influence prioritisation, but never close or delete a patient journey</div></div><Sparkles size={16} color="#c19038"/></div><div className="empty-page" style={{ boxShadow: "none" }}><div className="empty-icon"><Sparkles size={25}/></div><h2>No medical aid scoring options yet</h2><p>Add medical aid schemes and options before generating prioritised recall opportunities.</p></div></div></>;
}
