import { Activity, CalendarCheck, PhoneCall, Search, Send, Users } from "lucide-react";
import { team } from "@/lib/mock-data";

export function TeamActivity() {
  return <><div className="page-head"><div><h1>Team activity</h1><p>Real contact effort, patient outcomes and conversion quality across your branch.</p></div><button className="btn btn-primary"><Users size={14}/>Manage allocation</button></div>
  <div className="metric-grid" style={{gridTemplateColumns:"repeat(4,1fr)"}}>{[["Team online","3 / 4","1 away"],["Contact attempts today","268","+12% vs daily average"],["WhatsApps sent","80","29.9% of contact mix"],["Verified bookings","30","18.2% team conversion"]].map((row,i)=><div className={`metric-card ${["teal","blue","violet","orange"][i]}`} key={row[0]}><div className="metric-label">{row[0]}</div><div className="metric-value">{row[1]}</div><div className="metric-trend">{row[2]}</div></div>)}</div>
  <div className="toolbar"><div className="searchbar"><Search size={14}/><input placeholder="Search employee…"/></div><select className="select"><option>This month</option><option>This week</option><option>Today</option></select></div>
  <div className="card"><div className="card-head"><div><div className="card-title">Employee performance</div><div className="card-sub">All activity is sourced from immutable patient journey events</div></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Employee</th><th>Allocated</th><th>Contacted</th><th>Pending</th><th>Attempts</th><th>WhatsApps</th><th>Callbacks</th><th>Recorded</th><th>Verified</th><th>Conversion</th><th>Avg attempts / booking</th></tr></thead><tbody>{team.map(member=><tr key={member.name}><td><span className={`online ${member.status === "Away" ? "away" : ""}`}/><strong>{member.name}</strong></td><td>{member.allocated}</td><td>{member.contacted}</td><td>{member.allocated-member.contacted}</td><td>{member.attempts}</td><td>{member.whatsapp}</td><td>{member.callbacks}</td><td>{member.recorded}</td><td><strong>{member.verified}</strong></td><td><strong>{member.conversion}</strong></td><td>{(member.attempts/member.recorded).toFixed(1)}</td></tr>)}</tbody></table></div></div></>;
}
